### ISSUE TITLE
What about English name of cities and Gov ??

### ISSUE THREAD

**Issue by anonymous-persone** [Tech-Labs/egypt-governorates-and-cities-db#1]
### could you add english name of Gov and Cities and District ??

or if you can't please comment with the best and free resource of the api that i can fetch from it the english and arabic names

**Comment by mrkindy** [comment]
Please check the last update

**Comment by anonymous-persone** [comment]
### Thank you for your interest 

**but what about if i need to get all the districts inside each city ??
for example Cairo city has Madint Nacer district
Giza city has Bolak el dakror district ???**

### and what is your sources for the last update , i which source did you get the english names ??
