### ISSUE TITLE
what about districts inside the cities ????

### ISSUE THREAD

**Issue by anonymous-persone** [Tech-Labs/egypt-governorates-and-cities-db#2]
### Thank you for your interest 

**but what about if i need to get all the districts inside each city ??
for example Cairo city has Madint Nacer district
Giza city has Bolak el dakror district ???**

### and what is your sources for the last update , i which source did you get the english names ??

**Comment by mrkindy** [comment]
We don't have any sources, all of data we have collected it from official government data, If you find any source for districts please share it with us

**Comment by anonymous-persone** [comment]
للاسف هوانا مش لاقى اى مصدر للمناطق الداخلية فا عشان كدة انا سئلتك 
و لكن معلش عايز اعرف ازاى جمعتها من البينات الحكومية الرسمية هل تواصلت مع حد فى الكومة ادهالك ولا فضلت تجمعهم واحدة واحدة و تكتبهم اصل متهيئلى تكون خد ت الاختيار التانى لانه صعب تعمل كدة 
 ؟

فا انا عايز اعرف لو انت تواصلت مع حد من الحكومة عشان يدهملك طب ليه متعرفش تجيب بينات المناطق انجليزى و عربى ؟

**Comment by mrkindy** [comment]
المحافظات المصرية معروفة و اغلب المدن جمعناها من خلال البوابات الرسمية للمحافظات او من مواقع الوزارات زي وزارة الاستثمار الموجودة على الانترنت
بعض المعلومات اللي مكنتش متاحة في اي مصادر حكومية كنا بنستعين بمصادر زي ويكيبديا
لم نتواصل مع اي جهة او شخص و البيانات كلها مدخله بشكل يدوي

**Comment by anonymous-persone** [comment]
واو :1st_place_medal: 
انت بجد عظبم انت يعتبرمجمع 300 سطر يدوى يعنى مش من 
API 
او حاجة اوتوماتك 

ازاى جالك صبر تعمل كل ده  :smiley: 
ربنا يجعله فى مزان حسناتك 
و جزاك الله خيرا 

عمتا لو لقيت اى طريقة او عندك وقت فاضى تجمع المناطق كلها يبقا كتر خيرك بس انا حاسس انها موجودة بشكل اوتوماتك ولكن مش عارف اوصلها

**Comment by anonymous-persone** [comment]
ممكن تبعتلى اللنك المباشر بتاع البينات دى على موقع الوزارة الاستثمار انا دخلت عليه و لكن مش عارف انى صفحة فيها البينات دى 

@mrkindy

**Comment by mrkindy** [comment]
ده موقع تابع لوزارة التنمية المحلية
http://psm.gov.eg/
